version: '3.8'

services:
  nest:
    build:
      context: .
      dockerfile: nest.dockerfile
    ports:
      - ${APP_PORT}:3000
    command: yarn start:dev
    volumes:
      - ./src:/app/src
    depends_on:
      - redis
  redis:
    image: redis/redis-stack
    volumes:
      - redis-data:/data
      - ./conf/redis.conf:/redis-stack.conf
    # ports:
    #   - 8001:8001

volumes:
  redis-data: